name: Classroom
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Keygen
        run: |
          echo "Deploying to server..."
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          
      - name: Deploy
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            sudo docker compose -f docker-compose.yml down;
            cd lab3-template;
            git checkout master;
            git pull;
            sudo docker compose -f docker-compose.yml up -d --build;
            sudo docker ps -a;
            exit;

      - name: healthcheck
        run: ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050
          HOST: ${{ secrets.HOST }}
        continue-on-error: true

      - name: Run API Tests
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd lab3-template;
            ./scripts/test-script.sh v4 rating-service 8050;
            exit;
        
